<a href="https://colab.research.google.com/github/sameer-malik1/AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy Array

In [4]:
# importing numpy
import numpy as np

# creating a numpy array
a = np.array([1,2,3])
print(type(a))

# creating 2D and 3D array
b = np.array([[1,2,3],[4,5,6]])
print("2D Array",b)

c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3D Array: ",c)

<class 'numpy.ndarray'>
2D Array [[1 2 3]
 [4 5 6]]
3D Array:  [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [8]:
# dtype
boolArray = np.array([1,2,3], dtype=bool)
print(boolArray)

floatArray = np.array([1,2,3], dtype = float)
print(floatArray)

complexArray = np.array([1,2,3],dtype=complex)
print(complexArray)


[ True  True  True]
[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


In [12]:
# arange -> it defines the array starts from 1 and goes till range
np.arange(1,11)

# reshape -> it can change the order of defined numpy array
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
# creating the array of ones and zeros
np.ones((3,4))

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# generating random numbers and random numbers array
import random
ranNum = random.random()
print("Random # ",ranNum)

ranArray = np.random.random((3,4))
print("Random Array of 3 x 4: \n",ranArray)

Random #  0.24288868116602147
Random Array of 3 x 4: 
 [[0.8321604  0.38339681 0.23956468 0.62305894]
 [0.02938839 0.69692675 0.87097821 0.0408994 ]
 [0.03988161 0.04513001 0.92125516 0.58755927]]


In [21]:
# linspace -> used to create linear array of equidistant numbers np.linspace(startingNum,endingNum,numbersBetweenRanges)
np.linspace(-10,10,5)

# np.identity() -> creating identity matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# ndim -> finding the dimension of an array
np.ndim(np.array([1,3,5]))
np.ndim(np.array([[1,2],[3,4]]))

2

In [28]:
# shape -> finding how many elements in each of dimensions
np.shape(np.array([[1,2,3,4],[5,6,7,8]]))

(2, 4)

In [31]:
# size -> finding how many number of elements present in array
np.size(np.ones((3,4)))

12

In [36]:
# itemsize -> an attribute to find the site of item
np.array([1,2,3]).itemsize

# dtype -> an attribute to find data type of np array
np.array([1,2,3]).dtype

dtype('int64')

Changing datatypes

In [41]:
ages = np.array([18,19,20,22,24,25,27,30,40,50,60,70,85,93,99,110])
print(ages.dtype)
ages.astype(np.int32)

int64
int64


# Numpy Array Operations

In [46]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
# Scaler operations

# Arithmatic
print(a1 * 2)
print(a1 / 2)
print(a1 + 2)
print(a1 - 2)


# Relational: ==/<=/>=/!=
a1 > 3


[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
# Vector Operations: operations between two numpy arrays of same order

# Arithmatic
a1 + a2
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Numpy Array Functions

In [64]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[95. 65. 11.]
 [94. 33. 24.]
 [78. 62. 72.]]


In [65]:
# max/min/sum/prod
# 0 -> col , 1 -> row
np.max(a1,axis=0)

array([95., 65., 72.])

In [74]:
# mean/med/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

59.333333333333336
65.0
28.480012484391768
811.111111111111


In [76]:
# dot product
mat1 = np.arange(1,13).reshape(3,4)
mat2 = np.arange(13,25).reshape(4,3)

np.dot(mat1,mat2)  # note: no of col of 1st matrix = no of rows of 2nd matrix

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [77]:
# log and exp
np.exp(a1)

array([[1.81123908e+41, 1.69488924e+28, 5.98741417e+04],
       [6.66317622e+40, 2.14643580e+14, 2.64891221e+10],
       [7.49841700e+33, 8.43835667e+26, 1.85867175e+31]])

In [86]:
# floor/round/ceil
np.round(np.random.random((3,3))*100)

array([[51., 80., 72.],
       [ 7., 76., 56.],
       [18., 81., 54.]])

In [144]:
# indexing and slicing
arr1 = np.arange(24).reshape(4,6)
print(arr1[1,1])

# Fancy indexing
print(arr1[[0,2,3]]) # taking specific rows from 2d array

print(arr1[:,[0,1,5]]) # : refers to all of the rows, [0,1,5] shows the specific cols


# Boolean Indexing
import random
arr2 = np.random.randint(1,100,24).reshape(4,6)
arr2>30 # boolean array
arr2[arr2>30 ] # it is called boolean masking
arr2[(arr2>20) & (arr2%2 ==0)] # note: always use bitwise and(&) while dealing with boolean values
arr2[~(arr2%2==0)]


7
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  5]
 [ 6  7 11]
 [12 13 17]
 [18 19 23]]


array([69, 95, 87, 37, 41, 25, 87, 73, 91, 99, 21])

In [90]:
# Transpose
iMatrix = np.array([[1,2,3],[4,5,6]])
np.transpose(iMatrix)

# converting any dimention Matrix to 1D array
np.ravel(iMatrix)

array([1, 2, 3, 4, 5, 6])

**Stacking**

In [93]:
# Horizontal stacking
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

stackedArray = np.hstack((arr1,arr2))
stackedArray

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [95]:
# Vertical stacking
vStackedArray = np.vstack((arr1,arr2))
print(vStackedArray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


**Splitting**

In [100]:
# Horizontal splitting
np.hsplit(vStackedArray,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18],
        [21, 22]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20],
        [23, 24]])]

In [101]:
# Vertical splitting
np.vsplit(vStackedArray,2)

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

**Numpy vs Python list**

In [110]:
# speed difference

import time
intList1 = [i for i in range(10000000)]
intList2 = [i for i in range(10000000,20000000)]

c = []
start = time.time()
for i in range(len(intList1)):
  c.append(i)

print(time.time()-start)

1.288802146911621


In [111]:
import numpy as np

start = time.time()
numpyArray1 = np.arange(10000000)
numpyArray2 = np.arange(10000000,20000000)

c = numpyArray1 + numpyArray2
print(time.time()-start)

0.1433861255645752


In [113]:
# Memory allocation difference
import sys
pythonList = [i for i in range(10000000)]
sys.getsizeof(pythonList)

89095160

In [114]:
numpyList = np.arange(10000000,dtype=np.int32)
sys.getsizeof(numpyList)

40000112